sudo: required
services:
  - docker

before_install:
  - docker build -t praja/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run praja/react-test npm run test -- --coverage

after_success:
  - docker build -t praja/multi-client ./client
  - docker build -t praja/multi-nginx ./nginx
  - docker build -t praja/multi-server ./server
  - docker build -t praja/multi-worker ./worker
  
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push praja/multi-client
  - docker push praja/multi-nginx
  - docker push praja/multi-server
  - docker push praja/multi-worker

   
